// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8QRStryLvCyPd9Ew6RaMhhx3dPx8Tf5w',
    appId: '1:607294559860:web:6bef679c3ed54c2b89e321',
    messagingSenderId: '607294559860',
    projectId: 'health-tracker-84761',
    authDomain: 'health-tracker-84761.firebaseapp.com',
    storageBucket: 'health-tracker-84761.firebasestorage.app',
    measurementId: 'G-7XLPLCLM0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5qLsomTfol6Ts4TvjSkv4fBDwHAkffnk',
    appId: '1:607294559860:android:272013507fe5463889e321',
    messagingSenderId: '607294559860',
    projectId: 'health-tracker-84761',
    storageBucket: 'health-tracker-84761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNXItUu7Bi0E3jg5h0UH9CSKHz5YF9zQo',
    appId: '1:607294559860:ios:5c690a81dbf3656b89e321',
    messagingSenderId: '607294559860',
    projectId: 'health-tracker-84761',
    storageBucket: 'health-tracker-84761.firebasestorage.app',
    androidClientId:
        '607294559860-uoe9rl7qarr442j5k56ckrrb9urtpjka.apps.googleusercontent.com',
    iosClientId:
        '607294559860-08fpcbstl63ttbdq141ibqjh7i7lnhij.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNXItUu7Bi0E3jg5h0UH9CSKHz5YF9zQo',
    appId: '1:607294559860:ios:5c690a81dbf3656b89e321',
    messagingSenderId: '607294559860',
    projectId: 'health-tracker-84761',
    storageBucket: 'health-tracker-84761.firebasestorage.app',
    androidClientId:
        '607294559860-uoe9rl7qarr442j5k56ckrrb9urtpjka.apps.googleusercontent.com',
    iosClientId:
        '607294559860-08fpcbstl63ttbdq141ibqjh7i7lnhij.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8QRStryLvCyPd9Ew6RaMhhx3dPx8Tf5w',
    appId: '1:607294559860:web:1ebda0f81039311389e321',
    messagingSenderId: '607294559860',
    projectId: 'health-tracker-84761',
    authDomain: 'health-tracker-84761.firebaseapp.com',
    storageBucket: 'health-tracker-84761.firebasestorage.app',
    measurementId: 'G-VRGH2BB5CE',
  );
}
